server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web_demo?useUnicode=true&characterEncoding=utf8
    username: root
    password: root


  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    timeout: 60000
#    password: