server:
  port: 9020

spring:
  datasource:
    url: jdbc:mysql://172.16.0.10:3306/web_demo?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: 172.16.0.10
    timeout: 60000

security:
  hostname: localhost:${server.port}
  oauth2:
    client:
      id: ${security.oauth2.resource.id}
      client-id: client-authentication
      client-secret: abcdef
      # 此处设置只是为了在获取token的时候不报错
      scope: all
      access-token-uri: http://${security.hostname}/oauth/token
      user-authorization-uri: http://${security.hostname}/oauth/authorize
      client-authentication-scheme: header
    resource:
      id: ${spring.application.name}
      user-info: ${security.hostname}/user
      jwt:
        key-uri: ${security.hostname}/oauth/token_key

ribbon:
  readTimeout: 60000
  connectTimeout: 60000
feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000

swagger:
  basePackage: com.shishuheng.framework.authentication.controller
  title: 系统模块
  description: 系统核心部分的管理
  version: 1.0
  termsOfServiceUrl:
  contact:
    name: shishuheng
    email: 1136313573@qq.com
    url:

global:
  # 低内存模式
  lowMemoryMode: false
  # jwtAccessToken的signingKey
  signingKey:
