server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web_demo?useUnicode=true&characterEncoding=utf8
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    timeout: 60000

security:
  oauth2:
    client:
      client-id: first-client
      client-secret: noonewilleverguess
      access-token-uri: localhost:8080/oauth/token
      user-authorization-uri: localhost:8080/oauth/authorize
    resource:
      user-info: localhost:8080/user
      jwt:
        key-uri: localhost:8080/oauth/token_key

global:
  # 低内存模式
  lowMemoryMode: false
  # jwtAccessToken的signingKey
  signingKey:
